spring:
  datasource:
    url: jdbc:mysql://localhost:3309/user_info
    username: root
    password: password
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  flyway:
    baselineOnMigrate: true

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000

logging:
  level:
    root: DEBUG